### PR TITLE
Added AdminSidebar Component

### PR DESCRIPTION
**Pull request by RodolfoJaspe**
# Description

- What work was done?
Added AdminSidebar component to align with the AdminDashboard page. 

- Why was this work done?
The AdminSidebar routes the admin to all the admin pages

- What feature / user story is it for?
Addresses the sidebar feature for this [trello card](https://trello.com/c/PWdISCLn/819-as-an-admin-i-want-a-page-where-i-can-manage-our-site-so-that-i-can-have-a-secure-place-to-manage-the-site) 

- Any relevant links or images / screenshots

Wireframe for Admin Dashboard that displays AdminSidebar component on the left.
Screen Shot 2022-02-15 at 8 16 56 PM
Co-authored-by: @kyle-naumann @ORiveraJr84 

Initial rendering of Admin Dashboard that displays AdminSidebar component on the left.
Screen Shot 2022-02-15 at 8 21 34 PM
Co-authored-by: @Regbmiller 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes

[loom video](https://www.loom.com/share/692a159cadbe4b068170f4823177e487)

### CODE REVIEW

**Review by Kishkuman13 — COMMENTED** [review]
It looks like this is a continuation of a [previous pull request](https://github.com/BloomTech-Labs/scribble-stadium-fe/pull/375) that has not been merged. I'm not sure if we should wait get that pull request merged/resolved before merging this or not. Is there anything blocking us from merging the other pull request?

**Comment by RodolfoJaspe** [comment]
@Kishkuman13 Yes, this is a continuation of work after pull requests #375 and #376. #375 was just merged, so all good there. #376 I think should be merged before this one, that's the one on the AdminHeader.js file.

**Review by mattcasey879 — APPROVED** [review]
Code looks simple and easy understand, Good job!

**Review by Cyamos2 — APPROVED** [review]
Code looks great and love how the dashboard looks. Keep up the great work!

**Pull request merged**
