### PR TITLE
Feature/story manager

### PR DESCRIPTION
**Pull request by hamidash**
# Description

New Feature - Story Manager for Admins/Moderators

- What work was done?
   StoryManager component was built from scratch with functionalities to display story backlog, filter story backlog, show 
   story history, show story details as well as admins/moderators are able to reject or approve any story
   
- Why was this work done?
   As users upload content to the game app, there will be moderation to prevent inappropriate content to be displayed to 
   kids and moderator/admins of the website would like to be able to see, review, and approve/reject the submitted stories
- What feature/user story is it for?
  [Story Manager for admins and moderators](https://trello.com/c/Pj9zwD7V/882-as-an-admin-i-want-a-page-where-i-can-manage-our-site-so-that-i-can-have-a-secure-place-to-manage-the-site)
  
- Any relevant links or images/screenshots

> [**Loom Explanation**](https://www.loom.com/share/a6730cb12ca543dd9a8103e5c89fb509)

> **Components Screenshot**

image

 ⬇️  ⬇️  ⬇️  DEMO ⬇️  ⬇️  ⬇️

Scribble-StoryManager-review-v2 (1)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review, and merge

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by kyle-naumann — APPROVED** [review]
Wow, so much work has gone into this. It looks really clean and dry. Going through the code, I was impressed with how the state is handled all the way through the updates and changes. Really impressive work from all involved.

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Will have to remove the package-lock.json from this PR. It added 29,000 lines of code to this pull request. You should go into your terminal and run a `git checkout package-lock.json`. Then recommit the new package-lock to this PR.

**Review by Cyamos2 — APPROVED** [review]
Great job on using ant-card and adding specificity to each of the elements on them!

**Comment by hamidash** [comment]
> Will have to remove the package-lock.json from this PR. It added 29,000 lines of code to this pull request. You should go into your terminal and run a `git checkout package-lock.json`. Then recommit the new package-lock to this PR.

@ashtilawat23 I tried the instructions but it didn't add it in the commit. Can you pls help, with removing these 29,000 lines of changes? Am I missing something when following the instruction?

image

**Comment by quinn5moli** [comment]
Kudos for using semantic elements to ensure the app is more accessible. You did a great job making making your wireframe into a shippable feature.

**Pull request closed without merging**
