### PR TITLE
Richard rodriguez/single player mode

### PR DESCRIPTION
**Pull request by rmjuarez12**
# Pull Request Template

Single Player Mode game flow(Read, Draw, Write) is functional. In this PR, I am committing the changes done to the game files, which are under:

src/components/pages/Gameification

These files hold the entire game flow. Also, in the game flow, I am adding the voting steps as well. Note that the game flow is functional, however, it is not yet communicating with the backend. I am planning on working on that for my next PR. You can test the game by going to this URL once you start the application:

http://localhost:3000/gameification/

## Description

Add a summary that address the following:

- motivation/purpose for the feature
  To allow children to be able to skip the week long process, and instead, be able to play the game without waiting.
- What were those changes
  Finished the main functionality of the main game flow.
- What issues were fixed
  n/a

## Commits Checklist

- [x] commits have clear title names
- [x] commit has descriptive message of what has changed
- [x] more small commits than less big commits

## Code Checklist

- [x] code is formatted appropriately
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)
- [ ] no TODOS instead necessary comments
- [x] code follows Story Squad standards for:
  - Language
  - Framework
  - Libraries

### CODE REVIEW

**Comment by derekjpeters** [comment]
Can't wait to see it.  Do you care to send a demo of what you added?  Would love to see it in action.

**Review by derekjpeters — COMMENTED** [review]
Reviewed.  Big PR but this is pulling in what Richard has done.  I did request a demo loom from Richard to preview what he added.

**Comment by Rahmati1989** [comment]
Looks great changes. can't wait to see it in action. thanks everyone

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Great work here. Currently, there are merge conflicts with file already. Will probably have to keep this PR on hold temporarily. If you were to break this down into 4 different PRs, how would you break it down? Think of it as steps to tackling checking this PR and getting it reviewed.

**Comment by tinomen** [comment]
Has this been rebased from main recently? Like past couple days?

**Comment by rmjuarez12** [comment]
> Great work here. Currently, there are merge conflicts with file already. Will probably have to keep this PR on hold temporarily. If you were to break this down into 4 different PRs, how would you break it down? Think of it as steps to tackling checking this PR and getting it reviewed.

Alright. I will review the conflicts and assess them. I will first get the latest copy of the main branch to ensure I am up to date.

> Has this been rebased from main recently? Like past couple days?

Last time I did a fetch request to get the updated main branch was sometime mid-September. I will make sure to get the most updated version first to ensure all files I have are up-to-date.

**Comment by rmjuarez12** [comment]
I have fixed all the merge conflicts I was having.

**Review by ashtilawat — APPROVED** [review]

**Review by derekjpeters — APPROVED** [review]
Approved, merge conflicts are removed.  This is ready to be merged.

**Review by ashtilawat — APPROVED** [review]

**Pull request merged**
