### PR TITLE
fix Child Dashboard Progress Bar starting at the beginning

### PR DESCRIPTION
**Pull request by Fry-Fr**
• Removed hard coded data from completedActivity array.
• Changed current progress to appear on the correct day and activity.
Before
old_ChildDashboard
After
new_ChildDashboard

### CODE REVIEW

**Comment by Fry-Fr** [comment]
[Child Dashboard - Starts on Day 4 - Squad Up Needs to start at the correct Day](https://trello.com/c/KBBVAhLe/702-child-dashboard-starts-on-day-4-squad-up-needs-to-start-at-the-correct-day)

**Comment by ppmorgoun** [comment]
Nice PR Ryan! Good concise and atomic commits. The name of the PR could maybe be a little more reader friendly by rephrasing it in easy english (from "Bug/Child Dashboard Progress Bar-fix" to "Fixed Child Dashboard Progress Bar").
Also it says a check has be been failed - this should be looked into as well.

**Review by ppmorgoun — COMMENTED** [review]
Good atomic commit

**Review by ppmorgoun — APPROVED** [review]
Thanks for fixing the title - looks good

**Review by Kishkuman13 — COMMENTED** [review]
Looks good, however, isn't this now hardcoded to the beginning of the progress and days? I think this is something that needs to be dynamically rendered, based on some check function that retrieves their actual progress and the current day, but I don't see how that is being implemented.

**Comment by Fry-Fr** [comment]
this is not a functionality fix. Only an aesthetic fix. This is probably not adhering to DRY standards.

**Pull request closed without merging**
