### PR TITLE
Notification duedate

### PR DESCRIPTION
**Pull request by Bradleydion**
Looking to merge and get the folders set up.

## Commits Checklist
- [ x] commits have clear title names 
- [ x] commit has descriptive message of what has changed 
- [x ] more small commits than less big commits 

## Code Checklist 
- [ x] code is formatted appropriately 
- [ x] code meets DRY standards
- [ x] no dead code (check for logs and print statements)  
- [ x] no TODOS instead necessary comments 
- [ x] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries

### CODE REVIEW

**Comment by Bradleydion** [comment]
Looking to merge and get the folders set up.

**Review by kevinstonge — DISMISSED** [review]
nice starting point!

**Review by devandapaige — APPROVED** [review]
Great, just like we all discussed for a starting point. I look forward to seeing the other Notification Language as we need it. As more notifications are added, we may want to make these function names include the client, for example, StudentDueDate, etc.

**Review by MichelleCCodes — APPROVED** [review]
Great starting point - agreed! When tables and data is ready, there will need to be dynamic behavior later to accurately reflect the amount of days and number of activities left. Otherwise, looks great!

**Pull request merged**
