### PR TITLE
Feature/leaderboard to child gallery

### PR DESCRIPTION
**Pull request by greysonhamilton**
The feature has been added to gain access to the child's gallery page from the leaderboard.
The name within the leaderboard is now a link. Functionality works with the Ant Design module.

Thanks to Chucky who finished off the code for this task.

## Commits Checklist
- [ ] commits have clear title names 
- [ ] commit has descriptive message of what has changed 
- [ ] more small commits than less big commits 

## Code Checklist 
- [ ] code is formatted appropriately 
- [ ] code meets DRY standards
- [ ] no dead code (check for logs and print statements)  
- [ ] no TODOS instead necessary comments 
- [ ] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries   

### PRs needs to be reviewed by at least 2 team members
 - TPL is the 3rd reviewer 
 - Lots of comments and suggestions, please! 

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

### CODE REVIEW

**Review by clarejackson — DISMISSED** [review]
That is awesome that you got there with so little code! Nice work.

**Review by AniiGar — DISMISSED** [review]
Looks good Greyson!

**Review by dwainejade — DISMISSED** [review]
looks good

**Comment by chqiu6** [comment]
Good work Greyson.

**Review by AniiGar — APPROVED** [review]
Looks great Greyson!

**Review by dwainejade — APPROVED** [review]
Good job!

**Review by chqiu6 — APPROVED** [review]

**Pull request merged**
