### PR TITLE
Installed and added basic Audiobook player

### PR DESCRIPTION
**Pull request by Antashma**
Installed react-audio-player and added basic ReactAudioPlayer component to RenderAudioBook.js

### CODE REVIEW

**Review by sunkist5691 — APPROVED** [review]
Great job on adding react-audio-player.

**Review by kavya3v — APPROVED** [review]
Basic Audio player Component and import looks good.

**Review by silvodesigns — APPROVED** [review]
The component import looks good and so does the package.json file.

**Review by Claeb1mb — APPROVED** [review]
great!!

**Pull request merged**
