### PR TITLE
Spell Check - gamefication FIXED

### PR DESCRIPTION
**Pull request by artofmayhem**
All instances of gameification => gameifcation. I noticed that in the gamefication pages file there is an index file for clean exporting. Is there a reason that only one of the files in that folder is exported through this location?

### CODE REVIEW

**Comment by artofmayhem** [comment]
PR video submission https://youtu.be/eurZR28beY0
In reference to Trello Card https://trello.com/c/oaMqOtRM

**Review by venegasgabby76 — DISMISSED** [review]
thank you for fixing this. it will make things a lot clearer and easier to understand for all the people working on this project.

**Review by rhiannonstanford — DISMISSED** [review]
Nice work!  Thank you for being detailed and expedient!  Great attention to detail.

**Review by ethankarp — CHANGES_REQUESTED** [review]
Just need to change "gamefication" to "gameplay" now 👍

**Review by ethankarp — DISMISSED** [review]
gameplay is better, nice job 👍

**Review by milklot — DISMISSED** [review]
Looks good , good choice to simplify page naming, rep+

**Comment by artofmayhem** [comment]
> Just need to change "gamefication" to "gameplay" now 👍

all set and ready for merge

**Review by casey-dietz — APPROVED** [review]
Looks good, nice work on the updates!

**Comment by Yonathan-Admasu728** [comment]
Excellent job On making sure all instances of Gamefication has changed. great attention to detail

**Review by Yonathan-Admasu728 — COMMENTED** [review]
Excellent job in making sure all instances of gamefication has been changed. great attention to detail as always.

**Review by ethankarp — APPROVED** [review]

**Pull request merged**
