### PR TITLE
Feature/View prompt

### PR DESCRIPTION
**Pull request by AniiGar**
# View Prompt

Click on the View Prompt button to see PDF of source material for  the given week. 
    1. Use navigation buttons to select which page of the PDF to view. 
    2. Use scale buttons to zoom in and out of PDF. 
    3. Click Writing Prompt and Drawing Prompt to view the given assignments for that week. 

## Description
Created all of the functionality for the PDF viewer and the modal holding it to satisfy the need to see source material, writing and drawing prompts.
- What work was done?
    -- Created Weekly.js to move the label and create modal functionality. This card will be mapped over.
    -- Created PDFViewer.js to render a file. 
    -- Created PDFLoading.js to display if/when the file lags or does not load.
    -- Created ControlPanel.js to hold the page navigation and scale functionalities. 
    -- Created PromptButton.js to hold the buttons and functionality of the prompt buttons.

- Why was this work done?
    -- This work was done to provide the user with the source material for each week’s writing and drawing assignments. 

- What feature / user story is it for?
    -- As a user I would like a writing prompt to bring up source material
    -- https://trello.com/c/sp5JqCIs/64-add-button-for-writing-prompt 
### Type of change
This is a new feature adding functionality to the "View Prompt” button in the Gallery. It will display source material.

### Change Status
This feature is fully functional with styling in progress. Styling guides still need to be provided to complete the feature.  

### Has This Been Tested
I've tested the code in my local environment. Though, I have not added tests to the code. 

## Commits Checklist
- [x] commits have clear title names 
- [x] commit has descriptive message of what has changed 
- [x] more small commits than less big commits 

## Code Checklist 
- [x] code is formatted appropriately 
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)  
- [x] no TODOS instead necessary comments 
- [x] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries

### CODE REVIEW

**Review by dwainejade — DISMISSED** [review]
Good work!

**Review by greysonhamilton — DISMISSED** [review]
Great job! Looks good and clean.

**Review by dwainejade — DISMISSED** [review]

**Review by greysonhamilton — DISMISSED** [review]
This looks awesome!!
Great job!

**Review by dwainejade — APPROVED** [review]
Great job!

**Review by clarejackson — APPROVED** [review]
Looks so great; I am excited to see it with the kids' submissions!

**Pull request merged**
