### PR TITLE
Feature/fix htmlfor references

### PR DESCRIPTION
**Pull request by artofmayhem**
This pull request is meant to fix the htmlFor references in the codebase that were iterated as for in the label components of WordCloud/index.js lines 37 and 50 as well as ParentContactContainer.js lines 71, 83, 96

Pair coded with Rhiannon

this is in reference to trello card:                https://trello.com/c/g02KLUd7
the video for the pr is located:                   https://youtu.be/mRPvyx4yJEA

### CODE REVIEW

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Looks like the package-lock was committed. We can't have that being pushed up. Going forward only the files that are a part of the PR should be committed by doing git add fileName. We should do that file by file. Please remove the package-lock from the commit.

**Review by rhiannonstanford — CHANGES_REQUESTED** [review]
Self review for Tony & I.  We pair programmed this PR.  Tony, please remove the package-lock.json file from the PR.  We accidentally included it.  Thank you.

**Comment by artofmayhem** [comment]
deleted

**Review by rhiannonstanford — APPROVED** [review]
Self review.  Package-lock.json removed.  Pair programmed with Tony.

**Review by ethankarp — CHANGES_REQUESTED** [review]
We actually want to keep the package-lock.json file in the repository, we just don't want to push up any changes to it. You can see in main, there is a package-lock.json file, so we want to maintain that. If you cd into this branch and type "git checkout origin/main package-lock.json", it will restore the file as it is in main 👍

**Pull request closed without merging**
