### PR TITLE
Child Card - Parent Dashboard

### PR DESCRIPTION
**Pull request by brittanymclaughlin**
# Description

Fixes #

- What work was done? Child Card was created.
- Why was this work done? Because it was an integral part of the Parent Dashboard that the stakeholders wanted.
- What feature / user story is it for? 
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [-] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by tinomen** [comment]
Make sure to rename this PR with a descriptive title ;)

**Comment by tinomen** [comment]
Oh, and add the description with the motivation for the work and what changed

**Review by StefxM — DISMISSED** [review]
Looks good

**Review by StefxM — APPROVED** [review]
Updated - Looks better

**Review by charlene-johnson — APPROVED** [review]
Everything looks good! Like the child card designs!

**Review by cearc-sara — APPROVED** [review]
This looks great, well done!

**Pull request merged**
