### PR TITLE
Button and Contact us Fix

### PR DESCRIPTION
**Pull request by charlene-johnson**
# Pull Request Template

## Description
Add a summary that address the following:
 - motivation/purpose for the feature -Fixing things
 - What were those changes - Fixed the button hover and connected contact us page
 - What issues were fixed - Fixed the button hover so that its interactive when a user hovers over it, connected contact us page
 - Provide the link to the user story it is referencing in Trello board or other supporting document

## Commits Checklist
- [x] commits have clear title names 
- [x] commit has descriptive message of what has changed 
- [x] more small commits than less big commits 

## Code Checklist 
- [x] code is formatted appropriately 
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)  
- [ ] no TODOS instead necessary comments 
- [ ] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries   

### PRs needs to be reviewed by at least 2 team members
 - TPL is the 3rd reviewer 
 - Lots of comments and suggestions, please! 

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

### CODE REVIEW

**Review by StefxM — DISMISSED** [review]
Looks good!

**Review by RyanMersmann — DISMISSED** [review]
yes, looks amazing!

**Comment by leachtucker** [comment]
Looks good! You'll have to pull from main once again before merge

**Review by StefxM — APPROVED** [review]
Clean code ! looks good

**Review by RyanMersmann — APPROVED** [review]

**Pull request merged**
