### PR TITLE
Create pull_request_template.md file

### PR DESCRIPTION
**Pull request by elisan10**
Project repo now has a Pull Request Template so that team members have a template to go to when creating a new PR

### CODE REVIEW

**Review by Daemonlord92 — APPROVED** [review]
Direct and Simple I like it.

**Comment by askaborg** [comment]
Great you have everything that we agreed upon.

**Review by askaborg — APPROVED** [review]
This is a good initial draft.

**Comment by elisan10** [comment]
Sweet! As we start to do our pull requests if there's anything else that we notice we can jot those points down then add them to this template!

**Pull request merged**
