### PR TITLE
Feature/change look of single player button gamemode component

### PR DESCRIPTION
**Pull request by OniWarrior**
In this ticket, I changed the look of the single player component of gamemode component.

Reason for change:
The previous look was basically just a container with a little button at the center which was the link to start single player mode. It didn't look great and it didn't match the look and feel of the other buttons.

Changes made:
1. I removed the column, row container, and the boolean expression with the Link component. I have just a div container for the single player button and any other buttons that will be added in the future.
2.  I added a handler function for the new Button component to start the single player mode.
3. I thinned the border of the button.
4. Created scale up animation and added it to the hover pseudo class. I also put the scale value into the hover pseudo class rule set so that the button stays scaled up as long as the cursor is on the button.
5. I pushed down the container for the button by adding some padding to the padding-top property. This separates the button from the header at the top of the page.
6. Added the bangers and cursive font family to the class of the button. I also added some margin to the margin-left property to push the button slightly away from the left side of the page. Increased the width of the button and increased the font size of the single player text.
---------------------------------------------------------------------------------------------------------------
Note: when traversing the code base, I tested the GamemodeButton component. I'm 100 percent sure that this is an outdated component that is no longer being used. I believe that this component and the path to this component should be deleted. I didn't do it because that's not what the purpose of this branch was. My submission video has a more visual and detailed explanation to justify my case.

Trello Card: https://trello.com/c/MBKHEPCK/642-import-gameplaymain-from-components-pages-gameplay-index

PR submission video: https://drive.google.com/file/d/1idGDLgSCEnGC2jRO0w6ZW4bHL-MhajNi/view?usp=sharing

### CODE REVIEW

**Review by rhiannonstanford — DISMISSED** [review]
Nice attention to detail making this button more consistent in design to the overall app context.

**Review by mollybee — DISMISSED** [review]
The code is much cleaner and more readable for the button. The naming of your div and button containers are specific and make sense. Good job.

**Review by artofmayhem — DISMISSED** [review]
nice work on cleaning up the button functionality removing the trig() and replacing with a preventdefault push. 

also nice usage of keyframes to define the small animation action

**Review by MichaelMcFaddenjr — DISMISSED** [review]

**Review by artofmayhem — APPROVED** [review]
nice work on cleaning up the button functionality removing the trig() and replacing with a preventdefault push.

also nice usage of keyframes to define the small animation action

**Review by rhiannonstanford — APPROVED** [review]
Self Review

**Pull request merged**
