### PR TITLE
Repaired issue where trophy room background over extended past border

### PR DESCRIPTION
**Pull request by ORiveraJr84**
# Description

In child dashboard where the 4 main options are displayed, the Trophy Room option was displaying the background and text incorrectly. The "bang" background image would extend past the container bounds and the "Trophy Room!" text would sometimes not center when scaled to smaller screens. See screenshots below:

Bang BG extends past borders

Text not centered in container

- Motivation/purpose for the feature was to further improve and unify the visual experience for the user.
- Changes that were made:
  Removed unnecessary img element and altered style to match that of the accept the mission option on the same page.
- Issue that was fixed was noted in [this trello card](https://trello.com/c/f2tbPqx7/705-child-dashboard-trophy-room-leader-dashboard-border-overlap) that states that the background wasn't displaying correctly.

## Commits Checklist

- [x] commits have clear title names
- [x] commit has descriptive message of what has changed
- [x] more small commits than less big commits

## Code Checklist

- [x] code is formatted appropriately
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)
- [x] no TODOS instead necessary comments
- [x] code follows Scribble Stadium standards for:
  - Language
  - Framework
  - Libraries

### PRs needs to be reviewed by at least 2 team members

- TPL is the 3rd reviewer
- Lots of comments and suggestions, please!

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

### CODE REVIEW

**Comment by ORiveraJr84** [comment]
[Child Dashboard - Trophy Room/ Leader Dashboard Border Overlap](https://trello.com/c/f2tbPqx7/705-child-dashboard-trophy-room-leader-dashboard-border-overlap)

**Review by ghost — DISMISSED** [review]
I pulled your branch and looked at the changes. Very nice job making it more responsive!

**Review by brennanashley — DISMISSED** [review]
Thank you for fixing this so quickly!

**Review by ghost — APPROVED** [review]
Good work moving the image from the HTML file and making it a background image in the CSS.

**Review by ashtilawat — APPROVED** [review]

**Comment by brennanashley** [comment]
Thank you for fixing this!

**Pull request merged**
