### PR TITLE
Adjust styling to child dashboard gallery container

### PR DESCRIPTION
**Pull request by rhiannonstanford**
This pull request resolves styling updates to the child dashboard gallery container. 

1) Align cards - adjust Ant Design column element to sm={12}
2) Increase card border to .75rem (desktop) and .5rem (mobile)
3) Adjust clickable areas - move onClick to parent Col element
4) Add responsiveness - media queries added to ChildDashboard.less for container divs

Resolves Trello card: https://trello.com/c/LEnDVmG4/519-child-dashboard-update-styling-on-dashboard-container
PR video walkthrough: https://www.youtube.com/watch?v=UdMGI70uMWM

Pair-programmed  & Co-authored with Tony : @artofmayhem

### CODE REVIEW

**Review by rhiannonstanford — COMMENTED** [review]
Self review.

**Review by artofmayhem — APPROVED** [review]
Cleanly performant code on the media queries. Utilized onClick to make some cool and oddly functional clickable elements.

**Review by ethankarp — APPROVED** [review]
Awesome responsive Less additions!

**Review by Yonathan-Admasu728 — APPROVED** [review]
Wow! excellent choice on styling. code was very clear  and the video walkthrough was even better. I love how you add responsive features which counts mobiles and tablets in to consideration. Great Job. kudos to both of you.

**Review by chrislauyc — COMMENTED** [review]
Looks great!

**Pull request merged**
