### PR TITLE
Antd Tabs added to src/components/pages/NewParentDashboard/RenderNewParentDashboard.js

### PR DESCRIPTION
**Pull request by rockyFierro**
# Description

co-authored by: Rachel Van Tassel countrygirlr09@hotmail.com

Fixes #

- What work was done?
  Parent Dashboard was broken down into several easily accessible tabs to enhance readability and create a smoother user experience.
- Why was this work done?
    The previous layout drew attention to several objects at once. Flattening the information allows the reader to easily choose their focus and maintains each objects importance.
- What feature / user story is it for?
    Parent users.
- Any relevant links or images / screenshots
 [Trello Card](https://trello.com/c/AuiFIdxB)
 [PR Code Walk-thru](https://finnslighthouse.hippovideo.io/video/play/jydG9BnSOVEOeFz3Lozmjda0-E6YVWDH-cdUa3HWkU4?org_tok=V4xLYLG62XaDY3mcvgjRkA&utm_source=hv-campaigns&hreferer=private&hvre=false&_=1645345558731&)
## Updated Parent Dashboard
Alt Text

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by victoriatrac — APPROVED** [review]
Looks great, good job getting all of the React components placed into the new tabs also.

**Review by jdeltoro88 — COMMENTED** [review]
rocky this looks and operates very smoothly definitely an upgrade from back when i was working on this project, your code is clean and the video is very welll put together nicejob!

**Comment by Cyamos2** [comment]
Love how the page looks. The code on making the feel is very fluid and looks awesome! Great job guys!

**Review by Cyamos2 — COMMENTED** [review]
Saw how the code made the page fluid and look more lively. Great job guys!

**Review by KyleCardwell — APPROVED** [review]
Good re-design of the Parent Dashboard!  Smart move to switch to the antD tabs to keep with the same design language as the rest of the site.  Your code looks clean and the commits were easy to follow.

**Comment by Rachel311** [comment]
Your code is beautiful and flows nicely. I look forward to working with you more!!

**Review by Rachel311 — APPROVED** [review]
I'm impressed with what you accomplished here, especially just having learned Antd. Awesome job!

**Review by IsaacGHoward — APPROVED** [review]
Looks good, nice and easy simple changes to improve the layout. Love how the commits are very atomic.

**Pull request merged**
