### PR TITLE
Added photo for use as Auth0 logo

### PR DESCRIPTION
**Pull request by SethMacP**
Auth0 has their own built in IDE that requires a linkable photo to use for your logo on their prebuilt login tool. I am electing to store the photo in the repository for future use as well as host it for use on Auth0's website.

## Description
This photo was not hosted online as far as I could tell outside of Figma. I've included it in the codebase for future use on the frontend as well as creating a link for it to use on Auth0's website to utilize it as a logo.

The only changes made to this codebase were adding a .PNG file to the assets folder.

This will allow for more customization and personalization while using a 3rd party service.

Feel free to reference our task on Trello: https://trello.com/c/xPrsSrBr 
A view of the photo is available in the Trello card.

## Commits Checklist
- [x] commits have clear title names 
- [x] commit has descriptive message of what has changed 
- [x] more small commits than less big commits 

## Code Checklist 
- [NA] code is formatted appropriately 
- [NA] code meets DRY standards
- [NA] no dead code (check for logs and print statements)  
- [NA] no TODOS instead necessary comments 
- [NA] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries

### CODE REVIEW

**Review by allraec — CHANGES_REQUESTED** [review]
Hello Seth! I'm not able to see the file it would it be possible to show the image in the description for reference?

**Review by Antashma — APPROVED** [review]
Great!  I'm glad you followed Jake's suggestion!

**Comment by da-vazquez** [comment]
Great work @SethMacP! I like the idea of storing the image directly in the repo (as opposed to a 3rd party hosting service) so it can be reused by future cohorts. Only suggestion would be adding a link to preview the image somewhere in the PR description or the Trello Card.

**Review by allraec — APPROVED** [review]

**Review by da-vazquez — APPROVED** [review]
Thank you for adding the image to Trello!

**Pull request merged**
