### PR TITLE
Feature/game mode button

### PR DESCRIPTION
**Pull request by extrude575757**
# Pull Request Template

Go from a screen that selects the game play of single player or multiplayer. 
When the single player mode is selected it goes into the screen which gives the option to read, write, and/or draw. 
    1. You will be able to check or uncheck draw or write but cannot choose both write and draw together
    2. After chooseing you will be able to upload the drawing or writing to the platform. 
When it is submited a function will pit the player against a randomly chosen boss. 
## Description
Add a summary that address the following:
 - motivation/purpose for the feature 
     To make a gamemode menu for single player where they can choose read write or draw and then upload their writing or drawing
 - What were those changes
     A gamemode menu for uploading a drawing by choosing the button. 
 - What issues were fixed
     A gamemode styled menu
 - Provide the link to the user story it is referencing in Trello board or other supporting document
     https://trello.com/c/Q4Wusyn7/53-create-button-to-select-single-player-mode

## Commits Checklist
- [ ] commits have clear title names 
- [ ] commit has descriptive message of what has changed 
- [ ] more small commits than less big commits 

## Code Checklist 
- [ ] code is formatted appropriately 
- [ ] code meets DRY standards
- [ ] no dead code (check for logs and print statements)  
- [ ] no TODOS instead necessary comments 
- [ ] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries   

### PRs needs to be reviewed by at least 2 team members
 - TPL is the 3rd reviewer 
 - Lots of comments and suggestions, please! 

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

### CODE REVIEW

**Review by Daemonlord92 — DISMISSED** [review]

**Review by elisan10 — DISMISSED** [review]

**Review by jproctor-rebecca — CHANGES_REQUESTED** [review]
Please resolve merge conflict(s).

**Review by elisan10 — COMMENTED** [review]
We might have to change the layout of the read, write, draw buttons but this is great to work on for now! There are a couple files that have commented code that can probably be taken out. Can't wait to work with this code! Thanks for all the hard work!

**Review by elisan10 — APPROVED** [review]

**Comment by Daemonlord92** [comment]
I'm seeing a lines of commented code, we need to avoid that but other than that I think its looks great.

**Review by Daemonlord92 — APPROVED** [review]

**Review by askaborg — COMMENTED** [review]
Instead of "src/components/pages/Gamemode/UploaderComp.js" you should be able to use "src/components/pages/WritingSub/index.js" and "src/components/pages/DrawingSub/index.js" instead.

**Review by askaborg — COMMENTED** [review]
I feel bad, but we probably want to remove the "UploaderComp.js" since this will be redundant to " pages/DrawingSub/" and "pages/WritingSub/"; let's discuss.

**Review by jproctor-rebecca — APPROVED** [review]

**Pull request merged**
