### PR TITLE
Feature/dev ops

### PR DESCRIPTION
**Pull request by livytoolson**
# Description

Fixes #

- What work was done? Updated UI for Developer Mode pages and Admin Dashboard
- Why was this work done? UI makes it easier for user to navigate through the application.
- What feature / user story is it for? As a developer, I want to be able to pick a day of the week/game cycle to move the game into.
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by s-munro — APPROVED** [review]
Great job Livy!  This is a lot of progress

Just pulled from the branch and viewed with npm start -- looks good, I think the radio buttons get the job done as far as conveying and manipulating game state.  

Potential changes/future additions I could think of were removing the commented out code if/when you're done with it, some text-alignment tweaks (maybe resizing the radios in the future?), and merging the saturday-monday views if we verify those days are all the same functionality-wise (I believe they are).

This is all really great, let me know if you have any thoughts on those points!

**Comment by livytoolson** [comment]
> Great job Livy! This is a lot of progress
> 
> Just pulled from the branch and viewed with npm start -- looks good, I think the radio buttons get the job done as far as conveying and manipulating game state.
> 
> Potential changes/future additions I could think of were removing the commented out code if/when you're done with it, some text-alignment tweaks (maybe resizing the radios in the future?), and merging the saturday-monday views if we verify those days are all the same functionality-wise (I believe they are).
> 
> This is all really great, let me know if you have any thoughts on those points!

**Comment by livytoolson** [comment]
> Great job Livy! This is a lot of progress
> 
> Just pulled from the branch and viewed with npm start -- looks good, I think the radio buttons get the job done as far as conveying and manipulating game state.
> 
> Potential changes/future additions I could think of were removing the commented out code if/when you're done with it, some text-alignment tweaks (maybe resizing the radios in the future?), and merging the saturday-monday views if we verify those days are all the same functionality-wise (I believe they are).
> 
> This is all really great, let me know if you have any thoughts on those points!

Yes definitely agree with resizing the buttons, fixing some of the text-alignments, and potentially merging sat-mon. Just wanted to get a PR out there so you guys could have the updated code! I removed any code that was commented out and not needed. I left one onChange handler function commented out because we need that in the future for the radio buttons.

**Review by jbry0723 — APPROVED** [review]
All looks good to me.  Only thing is the entire ModerationTools.js is flagging as changed, assuming you reformatted or something, if not we may need to look into it.

**Comment by livytoolson** [comment]
> All looks good to me. Only thing is the entire ModerationTools.js is flagging as changed, assuming you reformatted or something, if not we may need to look into it.

Yeah I just did some reformatting, sorry I should've documented that better. I'll make sure to I've documented everything going forward.

**Review by ZEscanor — APPROVED** [review]

**Pull request merged**
