### PR TITLE
Bug/acceptTheMission-Header-fix

### PR DESCRIPTION
**Pull request by Fry-Fr**
# Pull Request Template

Go from a screen that selects the game play of single player or multiplayer.
When the single player mode is selected it goes into the screen which gives the option to read, write, and/or draw. 1. You will be able to check or uncheck draw or write but cannot choose both write and draw together 2. After chooseing you will be able to upload the drawing or writing to the platform.
When it is submited a function will pit the player against a randomly chosen boss.

## Description

Add a summary that address the following:

- motivation/purpose for the feature
  To make a gamemode menu for single player where they can choose read write or draw and then upload their writing or drawing
- What were those changes
  A gamemode menu for uploading a drawing by choosing the button.
- What issues were fixed
  A gamemode styled menu
- Provide the link to the user story it is referencing in Trello board or other supporting document
  https://trello.com/c/Q4Wusyn7/53-create-button-to-select-single-player-mode

## Commits Checklist

- [x] commits have clear title names
- [x] commit has descriptive message of what has changed
- [x] more small commits than less big commits

## Code Checklist

- [x] code is formatted appropriately
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)
- [x] no TODOS instead necessary comments
- [x] code follows Scribble Stadium standards for:
  - Language
  - Framework
  - Libraries

### PRs needs to be reviewed by at least 2 team members

- TPL is the 3rd reviewer
- Lots of comments and suggestions, please!

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

### CODE REVIEW

**Comment by Fry-Fr** [comment]
[Accept the Mission - The header Needs to be pulled in](https://trello.com/c/cm4gzwF1/710-accept-the-mission-the-header-needs-to-be-pulled-in)

**Comment by Fry-Fr** [comment]
trello card: https://trello.com/c/cm4gzwF1

**Comment by Fry-Fr** [comment]
Header component was being imported in YourMissionComp.js. So I added Header to render in the YourMissionComp.js component.

**Review by ghost — APPROVED** [review]
I was just about to complete a ticket for this when I saw that you already had. Nice catch!

**Pull request closed without merging**
