### PR TITLE
Feature/hud container

### PR DESCRIPTION
**Pull request by askaborg**
#This PR is for comments only

Added new component
* src/components/common/NewHud.js

Rendered NewHud in two components:
* src/components/common/NewProgressCharts.js
* src/components/pages/NewParentDashboard/RenderNewParentDashboard.js

Ashton can decide on which place looks better for the HUD.

### CODE REVIEW

**Comment by askaborg** [comment]
Do not merge until Ashton has completed styling and temp.txt is removed.

**Comment by askaborg** [comment]
NewHud

**Review by ashton-stom — CHANGES_REQUESTED** [review]
Just an update on this feature Hien. After the stakeholder meeting, I will be redoing this. Feel free to close this out.

**Comment by Jtamedrano** [comment]
changing from the destination branch from the main branch to freatue/headsupdevmaster

**Pull request closed without merging**
