### PR TITLE
feature/Add styling to the Play Again page

### PR DESCRIPTION
**Pull request by rhiannonstanford**
This PR adds styling to the Play Again page.
Screen Shot 2021-11-02 at 3 30 03 PM

### CODE REVIEW

**Review by rhiannonstanford — COMMENTED** [review]
Self review.

**Review by artofmayhem — CHANGES_REQUESTED** [review]
Check your animations GSAP runs on .from  => .to  and there are only .from statements in there. As another method you can just change your .from to fromTo() and accomplish the same thing. 
https://greensock.com/docs/v3/GSAP/gsap.fromTo()

check the documentation. otherwise SUPER CUTE PAGE!!!! love it. great job. nice and clean work.

**Review by ghost — APPROVED** [review]
Great job. I love the animation.

**Review by artofmayhem — APPROVED** [review]

**Review by milklot — APPROVED** [review]
Looks so cool, animation is fantastic. Great job!

**Pull request merged**
